PREP(addDesignatorActions);
PREP(canPickupDesignator);
PREP(canPlaceDesignator);
PREP(pickupDesignator);
PREP(placeDesignator);
PREP(populateChemlights);
PREP(dropChemlight);
PREP(canDropMarker);
PREP(handleFlare);