#define COMPONENT COMPONENTREGULAR
#define COMPONENT_BEAUTIFIED COMPONENTBEAUTIFIED
#include "RELATIVEPATH\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_COMPONENTUPPERCASE
  #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_COMPONENTUPPERCASE
  #define DEBUG_SETTINGS DEBUG_SETTINGS_COMPONENTUPPERCASE
#endif
#include "RELATIVEPATH\addons\main\script_macros.hpp"
